
# docker-compose.yml
#
# to start this stack run:
# docker-compose up
# docker-compose -d (detached mode)
# docker-compose logs (see logs)
# docker-compose stop (halt containers)
# docker-compose down (destroy containers)
# docker-compose down --volumes (destroy containers and volumes)

version: '3'

services:
  syncurity_postgresql:
    image: centos/postgresql-96-centos7:9.6
    container_name: syncurity_postgresql
    hostname: syncurity_postgresql
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    networks:
      - syncurity_network
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}

    volumes:
      - syn_st2_datastore.d:/docker-entrypoint-initdb.d

  syncurity_firewall_blocklists:
    image: quay.io/syncurity/syn-st2-flask
    container_name: syncurity_blocklists
    hostname: syncurity_blocklists
    ports:
      - "${EXTERNAL_BLOCKLIST_PORT}:8101"
    networks:
      - syncurity_network
    restart: always
    volumes:
      - syn_st2_blocklists/static:/app/static


networks:
  syncurity_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: ${SYNCURITY_ST2_NETWORK_SUBNET}

volumes:
  syn_st2_datastore.d:
  syn_st2_blocklists:
